all:
  children:
    turnkey:
      hosts:
        192.168.50.91:
    app_server:
      children:
        testing:
          hosts:
            192.168.50.92:
              ansible_ssh_private_key_file: /ansible/ssh/id_rsa
        staging:
          hosts:
            192.168.50.93:
              ansible_ssh_private_key_file: /ansible/ssh/id_rsa
